### ISSUE TITLE
Cards do not show for players and do not select for card czar

### ISSUE THREAD

**Issue by Note2Self** [ryanoverhauser/cards-against-idiots#2]
@ryanoverhauser  There is an issues when I start a game the cards don't show for the players and the card czar cannot pick any. 

Here is a screen shot

https://pasteboard.co/HwQu3G9.png

**Comment by ryanoverhauser** [comment]
@Note2Self @sean-james There was a missing property for black cards in the JSON decks that was causing the issue. Should be fixed now. Please pull the latest version.
